#!/bin/sh

mvn install:install-file -Dfile=lib/AXMLPrinter2.jar -DgroupId=soot \
    -DartifactId=axmlprinter -Dversion=2.0 -Dpackaging=jar

mvn install:install-file -Dfile=lib/asm-debug-all-5.0.3.jar -DgroupId=asm \
    -DartifactId=asm -Dversion=5.0.3 -Dpackaging=jar

mvn install:install-file -Dfile=lib/dexlib2-2.0.3-dev.jar -DgroupId=dexlib2 \
    -DartifactId=dexlib2 -Dversion=2.0.3 -Dpackaging=jar

mvn install:install-file -Dfile=lib/jasminclasses-2.5.0.jar -DgroupId=soot \
    -DartifactId=jasmin -Dversion=2.5.0 -Dpackaging=jar

mvn install:install-file -Dfile=lib/polyglotclasses-1.3.5.jar -DgroupId=soot \
    -DartifactId=polyglot -Dversion=1.3.5 -Dpackaging=jar

mvn install:install-file -Dfile=lib/sootclasses-rbclassload.jar -DgroupId=soot \
    -DartifactId=soot -Dversion=rb-1.0 -Dpackaging=jar

mvn install:install-file -Dfile=lib/pack.jar -DgroupId=org.trifort \
    -DartifactId=pack -Dversion=1.0 -Dpackaging=jar

mvn install:install-file -Dfile=lib/util-2.0.3-dev.jar -DgroupId=util \
    -DartifactId=util -Dversion=2.0.3 -Dpackaging=jar
