/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory */

#ifndef _Included_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
#define _Included_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadByteArray
 * Signature: ([BJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadByteArray
  (JNIEnv *, jobject, jbyteArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadBooleanArray
 * Signature: ([ZJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadBooleanArray
  (JNIEnv *, jobject, jbooleanArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadShortArray
 * Signature: ([SJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadShortArray
  (JNIEnv *, jobject, jshortArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadIntArray
 * Signature: ([IJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadIntArray
  (JNIEnv *, jobject, jintArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadFloatArray
 * Signature: ([FJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadFloatArray
  (JNIEnv *, jobject, jfloatArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadDoubleArray
 * Signature: ([DJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadDoubleArray
  (JNIEnv *, jobject, jdoubleArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadLongArray
 * Signature: ([JJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadLongArray
  (JNIEnv *, jobject, jlongArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteByteArray
 * Signature: ([BJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteByteArray
  (JNIEnv *, jobject, jbyteArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteBooleanArray
 * Signature: ([ZJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteBooleanArray
  (JNIEnv *, jobject, jbooleanArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteShortArray
 * Signature: ([SJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteShortArray
  (JNIEnv *, jobject, jshortArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteIntArray
 * Signature: ([IJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteIntArray
  (JNIEnv *, jobject, jintArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteFloatArray
 * Signature: ([FJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteFloatArray
  (JNIEnv *, jobject, jfloatArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteDoubleArray
 * Signature: ([DJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteDoubleArray
  (JNIEnv *, jobject, jdoubleArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteLongArray
 * Signature: ([JJII)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteLongArray
  (JNIEnv *, jobject, jlongArray, jlong, jint, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadByte
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadByte
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadBoolean
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadBoolean
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadShort
 * Signature: (JJ)S
 */
JNIEXPORT jshort JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadShort
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadInt
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadFloat
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doReadLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doReadLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteByte
 * Signature: (JBJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteByte
  (JNIEnv *, jobject, jlong, jbyte, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteBoolean
 * Signature: (JZJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteBoolean
  (JNIEnv *, jobject, jlong, jboolean, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteShort
 * Signature: (JSJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteShort
  (JNIEnv *, jobject, jlong, jshort, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteInt
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteInt
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteFloat
 * Signature: (JFJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteFloat
  (JNIEnv *, jobject, jlong, jfloat, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteDouble
 * Signature: (JDJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteDouble
  (JNIEnv *, jobject, jlong, jdouble, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory
 * Method:    doWriteLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_FastMemory_doWriteLong
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
