#!/bin/sh

cd ../../
ant jar
./pack-rootbeer

cd gtc2013/MegaMandel2/mandellib
ant jar
cd ../MegaMandel2/
ant jar
cd ..
java -jar ../../lib/pack.jar -mainjar MegaMandel2.jar -libjar mandellib.jar -destjar MegaMandel2-Packed.jar
java -jar ../../Rootbeer.jar MegaMandel2-Packed.jar MegaMandel2-GPU.jar
