#!/bin/sh

CFLAGS="-fno-common -Os -arch i386 -arch x86_64"
LDFLAGS="-arch i386 -arch x86_64 -dynamiclib"

llvm-gcc $CFLAGS -g -c -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I/usr/local/cuda/include/ org/trifort/rootbeer/runtime/FixedMemory.c -o FixedMemory2.o
llvm-gcc $LDFLAGS -o rootbeer_runtime_mac.dylib -dylib FixedMemory.o -lc -lcuda -L/usr/local/cuda/lib

llvm-gcc $CFLAGS -g -c -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I/usr/local/cuda/include/ org/trifort/rootbeer/runtime/CUDARuntime.c -o CUDARuntime.o
llvm-gcc $CFLAGS -g -c -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I/usr/local/cuda/include/ org/trifort/rootbeer/runtime/CUDAContext.c -o CUDAContext.o
llvm-gcc $LDFLAGS -o rootbeer_cuda_runtime_mac.dylib -dylib CUDARuntime.o CUDAContext.o -lc -lcuda -L/usr/local/cuda/lib

llvm-gcc $CFLAGS -g -c -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I/usr/local/cuda/include/ org/trifort/rootbeer/runtime/OpenCLRuntime.c -o OpenCLRuntime.o
llvm-gcc $CFLAGS -g -c -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I/usr/local/cuda/include/ org/trifort/rootbeer/runtime/OpenCLContext.c -o OpenCLContext.o
llvm-gcc $LDFLAGS -o rootbeer_opencl_runtime_mac.dylib -dylib OpenCLRuntime.o OpenCLContext.o -lc -lcuda -L/usr/local/cuda/lib
